import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";
import { readFileSync, writeFileSync } from "node:fs";
import { figletFontsDir, figletFontsPlugin } from "./scripts/figlet-fonts-plugin.mjs";
import { licenseNotices } from "./scripts/license-notices.mjs";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules,
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	plugins: [figletFontsPlugin()],
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
	metafile: prod,
});

if (prod) {
	const result = await context.rebuild();
	// Release builds carry the licenses of the packages bundled into them.
	// Dev builds skip this: prepending would shift the inline source map.
	const notices = licenseNotices([...Object.keys(result.metafile.inputs), `${figletFontsDir}/`]);
	writeFileSync("main.js", notices + readFileSync("main.js", "utf8"));
	process.exit(0);
} else {
	await context.watch();
}
